services:

  # Rabbitmq ##########################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    restart: always

  # MongoDB ###########################################################
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
    - 8081:8081
    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL:-mongodb://mongodb:mongodb@mongodb:27017}
    restart: always
    depends_on:
    - mongodb

  # # APP #######################################################
  # app:
  #   build:
  #     context: ../
  #     dockerfile: ./.docker/Dockerfile.debug
  #   container_name: app
  #   restart: always
  #   environment:
  #     MONGODB_URL: ${MONGODB_URL:-mongodb://mongodb:mongodb@mongodb:27017}
  #     MONGODB_DATABASE: ${MONGODB_DATABASE:-settings}
  #   ports:
  #   - "${PORT:-4000}:${PORT:-4000}"
  #   - "9229:9229"
  #   depends_on:
  #   - mongodb
  #   - redis