---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongodb-exporter
  name: app
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: app
          image: ${DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 4000
              protocol: TCP
              name: http
            - containerPort: 9229
              protocol: TCP
              name: debug
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4000
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 15
