---
apiVersion: v1
kind: Service
metadata:
  namespace: mongodb-exporter
  name: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http